export const listamenu = [
    {
        id:1,
        title:"Página principal",
        url:"/home",
        icon:"home",
        hr:false,
        sub:false
    },
    {
        id:2,
        title:"Anúncios",
        url:"/anuncios",
        icon:"picture_in_picture",
        hr:false,
        sub:false
    },
    {
        id:3,
        title:"Sites",
        url:"/sites",
        icon:"web",
        hr:true,
        sub:false
    },
    {
        id:6,
        title:"Relatorios",
        url:"/reports",
        icon:"insert_chart",
        hr:false,
        sub:false
    },

    {
        id:9,
        title:"URL Builder",
        url:"/urlbuilder",
        icon:"link",
        hr:false,
        sub:false
    },
    {
        id:10,
        title:"Conta",
        url:"/settings",
        icon:"settings",
        hr:false,
        sub:false
    },
    {
        id:11,
        title:"Atendimento",
        url:"/feedback",
        icon:"feedback",
        hr:false,
        sub:false
    },
]