export const listamenu = [
    {
        id:1,
        title:"Página principal",
        url:"/home",
        icon:"home",
        hr:false,
        sub:false
    },
    {
        id:2,
        title:"Anúncios",
        url:"/anuncios",
        icon:"picture_in_picture",
        hr:false,
        sub:false
    },
    {
        id:3,
        title:"Sites",
        url:"/sites",
        icon:"web",
        hr:true,
        sub:false
    },
    {
        id:4,
        title:"Privacidade e mensagens",
        url:"/privacy",
        icon:"manage_accounts",
        hr:false,
        sub:false
    },
    {
        id:5,
        title:"Brand safety",
        url:"/brand",
        icon:"block",
        hr:false,
        sub:false
    },
    {
        id:6,
        title:"Relatorios",
        url:"/reports",
        icon:"insert_chart",
        hr:false,
        sub:false
    },
    {
        id:7,
        title:"Otimizaçao",
        url:"/otimizacao",
        icon:"trending_up",
        hr:false,
        sub:false
    },
    {
        id:8,
        title:"Central de políticas",
        url:"/policy",
        icon:"policy",
        hr:true,
        sub:false
    },
    {
        id:9,
        title:"Pagamentos",
        url:"/payments",
        icon:"payments",
        hr:false,
        sub:true,
        open:false,
        submenu:[
            {
                id:12,
                title:"Pagamentos",
                url:"/payments",
                icon:"payments",
            }
        ]
    },
    {
        id:10,
        title:"Conta",
        url:"/settings",
        icon:"settings",
        hr:false,
        sub:false
    },
    {
        id:11,
        title:"Feedback",
        url:"/feedback",
        icon:"feedback",
        hr:false,
        sub:false
    },
]